baseURL = "/"
languageCode = "en-us"
relativeUrls = true
title = "Beefy Finance | Blog"
theme = "Beefy"

[sitemap]
filename = "hidden-sitemap.xml"

[params]
defaultTheme = "auto"
favicon = '= "./favicon.ico"'
disableThemeToggle = false
showFooterLinks = true

  [params.label]
  icon = "/beefy/beefy-cow.png"
  

  [params.fonts]
  ubuntu = "https://fonts.googleapis.com/css2?family=Ubuntu&display=swap"
  openSans = "https://fonts.googleapis.com/css2?family=Open+Sans&display=swap"

  [params.profileMode]
  enabled = true
  title = "Beefy Finance | Blog"
  subtitle = "Moo"

  [params.footer]
  blogName = "Blog"
  appName = "Beefy App"
  appURL = "https://app.beefy.finance"
  docsName = "Docs"
  docsURL = "https://docs.beefy.finance/beefyfinance/"
  voteName = "Vote"
  voteURL = "https://vote.beefy.finance/#/"
  dashboardName = "Dashboard"
  dashboardURL = "https://dashboard.beefy.finance/"
  artwork = "/footer/beefy-cows-and-hills.png"
  github = "/footer/github.svg"
  telegram = "/footer/telegram.svg"
  discord = "/footer/discord.svg"
  youtube = "/footer/youtube.svg"
  medium = "/footer/medium.svg"
  twitter = "/footer/twitter.svg"

  

[[menu.main]]
identifier = "articles"
name = "articles"
url = "/articles/"
weight = 10
