baseURL: "/"
languageCode: "en-us"
theme: Beefy
relativeUrls: true
title: Beefy

sitemap:
  filename: hidden-sitemap.xml

params:
  disableThemeToggle: false
  defaultTheme: auto
  favicon: = "./favicon.ico"

  fonts:
    ubuntu: "https://fonts.googleapis.com/css2?family=Ubuntu&display=swap"
    openSans: "https://fonts.googleapis.com/css2?family=Open+Sans&display=swap"

  profileMode:
    enabled: true
    title: Beefy Blog
    subtitle: Moo

# menu:
#     main:
#         - identifier: categories
#           name: categories
#           url: /categories/
#           weight: 10
#         - identifier: tags
#           name: tags
#           url: /tags/
#           weight: 20

