baseURL = "/"
languageCode = "en-us"
relativeUrls = true
theme = "Beefy"
title = "Beefy"
[params]
defaultTheme = "auto"
disableThemeToggle = false
favicon = "= \"./favicon.ico\""
[params.fonts]
openSans = "https://fonts.googleapis.com/css2?family=Open+Sans&display=swap"
ubuntu = "https://fonts.googleapis.com/css2?family=Ubuntu&display=swap"
[params.profileMode]
enabled = true
subtitle = "Moo"
title = "Beefy Blog"
[sitemap]
filename = "hidden-sitemap.xml"
