baseURL = "/"
languageCode = "en-us"
theme = "Beefy"
relativeUrls = true
title = "Beefy"

[sitemap]
filename = "hidden-sitemap.xml"

[params]
disableThemeToggle = false
defaultTheme = "auto"
favicon = '= "./favicon.ico"'

  [params.fonts]
  ubuntu = "https://fonts.googleapis.com/css2?family=Ubuntu&display=swap"
  openSans = "https://fonts.googleapis.com/css2?family=Open+Sans&display=swap"

  [params.profileMode]
  enabled = true
  title = "Beefy Blog"
  subtitle = "Moo"
